# name
name: CI

# triggers
on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".editorconfig"

# jobs
jobs:
  # build
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: |
          cid workflow run --stage build
  # test
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: test
        run: |
          cid workflow run --stage test
  # lint
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: lint
        run: |
          cid workflow run --stage lint
